# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.1
  hooks:
    - id: ruff-check
      name: Ruff Python Linting
      args: [--fix]
      always_run: true
    - id: ruff-format
      name: Ruff Python Formatting
      always_run: true

- repo: local
  hooks:
    - id: Ty
      name: Ty Python Type Checking
      entry: uvx ty check src --error-on-warning
      always_run: true
      language: system
      pass_filenames: false
    - id: UV Lock
      name: UV Lock
      entry: uv lock
      always_run: true
      language: system
      pass_filenames: false
